apiVersion: apps/v1
kind: Deployment
metadata:
    name: kansasprojectsbx3-deployment
    labels:
        app: kansasprojectsbx3
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kansasprojectsbx3
    template: 
        metadata:
            labels:
                app: kansasprojectsbx3
        spec:
            containers:
            - name: k8s-demo
              image: acrsbx3.azurecr.us/kansasprojectsbx:latest
              ports:
              - containerPort: 80
            imagePullSecrets:
            - name: regcred
---
apiVersion: v1
kind: Service
metadata:
    name: kansasprojectsbx3
    annotations: 
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-dns-label-name: kansasprojectsbx3
    labels:
        app: kansasprojectsbx3
spec:
    ports:
        - name: http-port
          port: 80
          targetPort: 80
    selector: 
        app: kansasprojectsbx3
    type: LoadBalancer

