apiVersion: apps/v1
kind: Deployment
metadata:
    name: dep-kaecses-sbx-1
    labels:
        app: srv-kaecses-sbx-1
spec:
    replicas: 1
    selector:
        matchLabels:
            app: srv-kaecses-sbx-1
    template: 
        metadata:
            labels:
                app: srv-kaecses-sbx-1
        spec:
            containers:
            - name: k8s-demo
              image: acrsbx3.azurecr.us/repkaecsesdev1:latest
              ports:
              - containerPort: 80
            imagePullSecrets:
            - name: regcred
---
apiVersion: v1
kind: Service
metadata:
    name: srv-kaecses-sbx-1
    annotations: 
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-dns-label-name: srv-kaecses-sbx-1
    labels:
        app: srv-kaecses-sbx-1
spec:
    ports:
        - name: http-port
          port: 80
          targetPort: 80
    selector: 
        app: srv-kaecses-sbx-1
    type: LoadBalancer

